name: deploy to lambda

on:
    push:
        branches:
            - main
    pull_request:

jobs:
   deploy:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./sam-app/hello-world
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Configure AWS Credentials
              run: |
                export AWS_ROLE_ARN=${{ secrets.AWS_ROLE_ARN }}
                export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
                export AWS_DEFAULT_REGION=ap-northeast-1

                echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
                echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
                echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV

                curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                python-version: 3.9
            - run: npm install
            - run: zip -r package.zip ./*
            - run: pip3 install awscli
            - run: aws lambda update-function-code --function-name hello-world-nodejs --zip-file fileb://package.zip --publish
